### ISSUE TITLE
As a User I want to be able to browse for available items

### ISSUE THREAD

**Issue by zachariyaJaveri** [Kas73/SOEN-341-Project#17]
Story Points: 15

Acceptance Tests:
- [ ] Should be able be able to browse products by category
- [ ] User should be able to search for a product
- [ ] Check a single product's details
- [ ] User should be able to login
- [ ] User should be able to create an account
- [ ] Administrative user should be able to add products to the site

**Comment by zachariyaJaveri** [comment]
All components have now been merged
