### ISSUE TITLE
As a User I want to be able to add products to my cart so that I may purchase them later

### ISSUE THREAD

**Issue by zachariyaJaveri** [Kas73/SOEN-341-Project#18]
Story Points: 10

Acceptance tests:
- [ ] User should be able to choose the quantity of an item that they are adding to their cart
- [ ] User should be able to view their cart
- [ ] User should be able to modify the quantity of an item in their cart
- [ ] User should be able to remove an item from their cart
- [ ] User's cart should persist when switching pages

**Comment by zachariyaJaveri** [comment]
all components have been merged
