### ISSUE TITLE
As a User I want to be able to place an order and manage it

### ISSUE THREAD

**Issue by zachariyaJaveri** [Kas73/SOEN-341-Project#19]
Story Points: 15

Acceptance test:
- [ ] User should be able to add a payment method to their account
- [ ] User should be able to add a shipping address to their account
- [ ] User should be able to see the subtotal of all their items including tax and shipping fees
- [ ] User should be able to place their order and see a confirmation
- [ ] User should be able to view their current orders
- [ ] User should be able to cancel an order
- [ ] A user's order history should persist between sessions
